### ISSUE TITLE
Invalid tenant id. Tenant have been mutated in lowercase, and this is bad.

### ISSUE THREAD

**Issue by bampnet** [mvertopoulos/vue-msal#24] opened 2020-05-08 18:10 UTC
Hi @mvertopoulos ,
the tenandId have been converted in a lowercase string. The assignment is correct.

The configuration:
`Vue.use(msal, {
  auth: {
    clientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    tenantId: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    redirectUri: 'localhost:8080',
    validateAuthority: false,
  }
});`

Request URL: https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxx/v2.0/.well-known/openid-configuration 400 Bad Request

`{
   "error":"invalid_tenant",
   "error_description":"AADSTS90002: Tenant 'xxxxxxxxxxxxx' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: **********************************\r\nCorrelation ID: ******************************\r\nTimestamp: 2020-05-08 17:54:51Z",
   "error_codes":[
      90002
   ],
   "timestamp":"2020-05-08 17:54:51Z",
   "trace_id":"**********************************",
   "correlation_id":"***********************************",
   "error_uri":"https://login.microsoftonline.com/error?code=90002"
}`

**Comment by mvertopoulos** [comment] 2020-06-30 14:49
Duplicate of #11

**Closed by mvertopoulos** 2020-06-30 14:49 UTC
