### ISSUE TITLE
Ability to override options in signIn() calls

### ISSUE THREAD

**Issue by baSSiLL** [mvertopoulos/vue-msal#17] opened 2019-12-26 10:26 UTC
Hi @mvertopoulos 
Nice work with the lib! However, I miss an ability to override options for authentication requests (**signIn** method).
My case is using AD B2C and necessity to invoke different policies (user flows). As you likely know, for B2C a policy name is embedded into authority URL. Thus ultimately I need to pass different **authority** value for **loginRedirect()** call of MSAL object which is possible using their **request** parameter. However, vue-msal lacks this capability in **signIn()** method.
The most straightforward solution would be to add a **request** parameter to **signIn()** which is simply forwarded to **loginRedirect()** of underlying msal object. Similarly to that existing in **acquireToken()** method. If you agree with such implementation I can make a pull request with these changes.
As a side note. What was the reasoning for splitting original **authority** option from msal into **tenantName** and **tenantId**? IMO it makes some confusion for users of msal. I needed to look into source code to figure out which part of authority to place in which of those options.

**Comment by allfro** [comment] 2020-04-25 03:38
The `authority` option should be allowed in the plugin. Otherwise it breaks some of the functionality with B2C and custom user flows. We cannot use it the way this has been designed at the moment.

**Comment by mvertopoulos** [comment] 2020-06-30 14:49
Duplicate of #11

**Closed by mvertopoulos** 2020-06-30 14:49 UTC
