### ISSUE TITLE
Incorrect discovery endpoint

### ISSUE THREAD

**Issue by ankur198** [mvertopoulos/vue-msal#10] opened 2019-11-25 17:53 UTC
I have configured options as 

``` javascript
new MSAL(
      {
        auth: {
          clientId: 'cfb536c3-057a-4d15-8283-91fcd5101c50',
          // tenantId: '3f4cc564-facc-4cef-bb21-415cf301f9d3',
          tenantId: 'virtualcollegebyankur.onmicrosoft.com',
          tenantName: 'virtualcollegebyankur.b2clogin.com',
          validateAuthority: false,
          redirectUri: 'localhost:3000'
        },
        framework: {
          globalMixin: true
        }
      },
```

And still it goes to common discovery endpoint

![image](https://user-images.githubusercontent.com/19951777/69565076-371a9e80-0fda-11ea-90ee-43145874b147.png)

It should go to url [https://login.microsoftonline.com/virtualcollegebyankur.onmicrosoft.com/v2.0/.well-known/openid-configuration](https://login.microsoftonline.com/virtualcollegebyankur.onmicrosoft.com/v2.0/.well-known/openid-configuration)

Am I missing something? Config setting?

**Comment by ankur198** [comment] 2019-11-25 20:32
Found that removing `tenantName` solves the issue

**Comment by mvertopoulos** [comment] 2020-06-30 14:47
Duplicate of #11

**Comment by mvertopoulos** [comment] 2020-06-30 14:48
Duplicate of #11

**Closed by mvertopoulos** 2020-06-30 14:48 UTC
